<?php include '_salutation.phtml' ?>

<?= sprintf(
    $this->translate('Please click on the following link to change your password.<br /><br />%s'),
    '<a href="' . $this->url('small-user-auth', ['action' => 'pw-lost-confirm', 'code' => $this->code], ['force_canonical' => true]) . '">
        ' . $this->url('small-user-auth', ['action' => 'pw-lost-confirm', 'code' => $this->code], ['force_canonical' => true])
    . '</a>'
)
?>