<?php

/** @var \GameBackend\Entity\Game\InventoryInterface[] $inventoryList */
$inventoryList = [
    1 => null,
    3 => null,
    0 => null,
    2 => null,
    4 => null,
];

/** @var \GameBackend\Entity\Game\InventoryInterface $inventorySlot */
foreach ($this->inventoryList as $inventorySlot) {
    $inventoryList[$inventorySlot->getSlot()] = $inventorySlot;
}

?>

<h2><?= $this->translate('InventoryAvatar') ?></h2>
<div class="table-responsive">
    <table class="table table-borderless table-inventory">
        <?php
        $i = 0;
        foreach ($inventoryList as $inventorySlot) :
            ?>
            <?= $i == 0 ? '<tr>' : '' ?>
            <?php if ($inventorySlot) { ?>
            <td><?= $this->pServerRankingItemDetails($inventorySlot->getItem()) ?></td>
        <?php } else { ?>
            <td>
                <div class="sro-item-detail">
                    <div class="item"></div>
                    <div class="clearfix"></div>
                </div>
            </td>
        <?php } ?>
            <?= $i == 1 ? '</tr>' : '' ?>
            <?php
            $i++;

            if ($i >= 2) {
                $i = 0;
            }

        endforeach;
        ?>
    </table>
</div>
