<?php
if ($this->uniqueKillList) :
    ?>
    <div>
        <h3><?= sprintf($this->translate('Last %s Unique Kills'), $this->limit) ?></h3>
        <hr/>
        <ul class="list-unstyled">
            <?php
            /** @var \PServerCMS\SROUnique\Shard\Entity\UniqueKillList $uniqueKill */
            foreach ($this->uniqueKillList as $uniqueKill) :
                ?>
                <li>
                    <?= sprintf(
                        $this->translate('%s has killed %s %s ago'),
                        '<a href="' . $this->url('PServerRanking/character', ['id' => $uniqueKill->getCharacter()->getId()]) . '"><b>' . $this->escapeHtml($uniqueKill->getCharacter()->getName()) . '</b></a>',
                        '<b>' . $this->escapeHtml($uniqueKill->getUniqueInfo()->getName()) . '</b>',
                        $this->agoTimerPServerCore($uniqueKill->getTime())
                    ) ?>
                </li>
                <br>
            <?php
            endforeach;
            ?>
        </ul>
    </div>
<?php
endif;
?>