<div class="card card-default mb-3">
    <div class="card-header"><?= $this->translate('Block History') ?> <small><?= $this->translate('last') ?> 10</small></div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-condensed">
                <tr>
                    <th>#</th>
                    <th><?= $this->translate('Reason') ?></th>
                    <th><?= $this->translate('Ban until') ?></th>
                </tr>
                <?php /** @var \PServerCore\Entity\UserBlock $blockHistory */ ?>
                <?php foreach ($this->blockHistoryList as $blockHistory) : ?>
                <tr>
                    <td><?= $blockHistory->getId() ?></td>
                    <td><?= $this->escapeHtml($blockHistory->getReason()) ?></td>
                    <td><?= $this->dateTimeFormatTime($blockHistory->getExpire()) ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>